apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    namespace 'ru.orangesoftware.financisto.storage.impl'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                    "room.schemaLocation": "$projectDir/schemas".toString(),
                    "room.incremental"   : "true"
                ]
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    
    // Configure kapt to use same Java version
    kapt {
        javacOptions {
            option("-source", Config.jvmTarget)
            option("-target", Config.jvmTarget)
        }
    }
}

dependencies {
    implementation project(':storage-api')
    
    // Room
    implementation "androidx.room:room-runtime:2.5.1"
    implementation "androidx.room:room-ktx:2.5.1"
    kapt "androidx.room:room-compiler:2.5.1"
    
    // Core dependencies
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.20'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1'
}
