plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'ru.orangesoftware.financisto.repository.impl'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation project(':repository-api')
    implementation project(':storage-api')
    
    // Core dependencies
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.8.20'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1'

    implementation 'io.insert-koin:koin-android:3.4.3'
    // Testing
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.1'
    testImplementation 'io.mockk:mockk:1.13.5'
    testImplementation 'com.google.truth:truth:1.1.5'
}
