plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'ru.orangesoftware.financisto.storage.api'
    compileSdk Versions.compileSdk

    defaultConfig {
        minSdk Versions.minSdk
        targetSdk Versions.targetSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.20"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
}
